### ISSUE TITLE
Project pushed to heroku!

### ISSUE THREAD

**Issue by jashieh** [jashieh/dimension-dxd#2]
I pushed up my project to heroku for feedback. Thanks!

https://mysticmessenger.herokuapp.com/#/

**Comment by evhumphrey** [comment]
@jashieh I'll take a look, thanks! 

Can you open an issue called `PA Review: User Auth` and assign me to the issue? It will help keep feedback organized by MVP.

I'll close this issue when the other one is created and assigned to me! ✅

**Comment by evhumphrey** [comment]
@jashieh Did the url change for heroku? It says "There's nothing here, yet"

**Comment by jashieh** [comment]
Yeah I sent the new link in the other issue!

**Comment by jashieh** [comment]
https://dimension-dxd.herokuapp.com/#/
