### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by jashieh** [jashieh/dimension-dxd#3]

**Comment by evhumphrey** [comment]
# User Auth Feedback

Good job :tada:! I have some feedback (I may add more, but this is currently the changes you should make)

## General

- [x] I'd give your splash a `min-height` of `100vh`, and change the background to black (I like `#252525`; right now, as the video loads, there is a weird half-of-the-page is a blue green gray color, and the rest is white. 
- [x] I'd add a background (use same color you use in previous task) for your `.login-signup-page` for a similar issue

## `/` frontend route (homepage/splash)

- [x] Remove the `Voice chat for virgin engineers` line; it could be considered unprofessional
- [x] Change`Discord` to `MysticMessenger` or maybe just `Mystic`
  - [x] Change the `Discord` in your nav
  - [x] Change the `Discord` in your button for `Open Discord in your Browser`

## `/login` & `/signup` frontend routes

- [x] The `Discord` floating near the top left doesn't look styled, and should be renamed to `MysticMessenger` or `Mystic` (or have a logo here)
- [x] Your inputs should use `box-sizing: border-box` so when you hover, they don't shift around
- [x] Render errors (they don't show up at all)
- [x] I recommend adding a `box-shadow` to your div holding the form, it will add a bit of separation between your form and the background

Box-shadow: 

![Screen Shot 2019-11-06 at 4 01 35 PM](https://user-images.githubusercontent.com/6361824/68348475-c523f900-00ae-11ea-9a22-44961ed1e8bd.png)


## Demo Login

- [x] Add a demo button to allow quick logging in 
- [x] I recommend adding it next to the Login button 

## When logged in, `/home`

- [x] You need a logout button. I recommend putting it at the very bottom of the server index sidebar (You can leave the other one you have at `/`, but you also need one here)

**Comment by jashieh** [comment]
Whoops a lot of the things on the splash page and login were all placeholders so while I decided on a theme I'll go back and fix them

**Comment by jashieh** [comment]
Is the background video rendering correct? for me there is no background at all besides the video
